insert into kb_docs(title, body, source, role_scope) values
  ('Admissions GPA rule',
   'Applicants with a prior GPA above 3.0 are auto-accepted, subject to program quota. Below 3.0 the registrar may still admit you but must justify the decision in writing.',
   'Handbook § 2.1', '{visitor,student,instructor,registrar}'::role[]),
  ('Registration limits',
   'Each matriculated student must register for between 2 and 4 courses per term. Fewer than 2 triggers a warning; the cap of 4 is hard.',
   'Handbook § 4.2', '{visitor,student,instructor,registrar}'::role[]),
  ('Taboo word policy',
   'Reviews with 1–2 taboo words are published with those words masked, and the author receives 1 warning. 3+ taboo words → review hidden entirely + 2 warnings.',
   'Handbook § 6.3', '{visitor,student,instructor,registrar}'::role[]),
  ('Graduation eligibility',
   'Students who have completed 8 classes may apply for graduation. The registrar verifies all required courses are covered. An incomplete application is penalised with 1 warning for reckless filing.',
   'Handbook § 7', '{visitor,student,instructor,registrar}'::role[]),
  ('Review policy',
   'Only students currently enrolled in a class may review it, 1 star (worst) to 5 (best). Reviews are anonymous to everyone except the registrars and close when the instructor posts a grade.',
   'Handbook § 6', '{visitor,student,instructor,registrar}'::role[]),
  ('Honor roll',
   'Semester GPA ≥ 3.75 or cumulative GPA ≥ 3.50 (after more than one semester) earns honor-roll status automatically. Each honor can retire one active warning.',
   'Handbook § 5.4', '{visitor,student,instructor,registrar}'::role[]),
  ('Semester phases',
   'The semester is divided into 4 periods: Class set-up → Course registration → Class running → Grading. Each phase enables specific actions and locks others.',
   'Handbook § 3', '{visitor,student,instructor,registrar}'::role[]),
  ('Drop / withdraw',
   'Dropping is not allowed during the class-running period (Feb 3 – Apr 20) except via the special registration window triggered when a course is cancelled. Contact the registrar for an exception.',
   'Handbook § 4.3', '{student,instructor,registrar}'::role[]),
  ('Class cancellation',
   'Courses with fewer than 3 students are cancelled at the end of the registration phase. Instructors whose ALL courses are cancelled are suspended and may not teach next semester.',
   'Handbook § 4.4', '{student,instructor,registrar}'::role[]),
  ('Suspensions and fines',
   'Any student receiving 3 active warnings is suspended for 1 semester and must pay a $250 reinstatement fine to the registrar.',
   'Handbook § 7.3', '{student,registrar}'::role[]);
